### ISSUE TITLE
7.3の評価指標のn-gramの説明

### ISSUE THREAD

**Issue by tomohideshibata** [ghmagazine/llm-book#15]
7.3の評価指標のn-gramの説明で、以下の説明が何回か繰り返されています。確認したのは電子版なのですが、電子版だけかもしれません。

> n=のときはユニグラム（unigram）、n=のときはバイグラム（bigram）、n=のときはトライグラム（trigram）..

**Comment by ikuyamada** [comment]
ご指摘をいただきありがとうございます。
epub作成時に起きた問題とのことで、修正して第2刷を発行する予定です。

**Comment by ikuyamada** [comment]
[正誤表に掲載](https://github.com/ghmagazine/llm-book/wiki/errata)させていただきましたので、こちらはcloseさせていただきます。
