### ISSUE TITLE
第9章サンプルコードのopenaiパッケージについて

### ISSUE THREAD

**Issue by tomitomi3** [ghmagazine/llm-book#26]
* 概要

最新のopenaiパッケージを使用すると9章のコードが動かない。コメントでどこか補足してもらうと良いかなと思いました。

* 原因と対応策

新しいopenaiパッケージはAPIが変更されているため。

既存のコードを試しながら読む場合は意図的に古いバージョンを使用する。0.27で試して実行できることを確認しました（出力エラーを見ると0.28でも動きそう）。

> !pip install datasets openai==0.27 tiktoken tqdm

* 参考

openaiパッケージのバージョン

https://pypi.org/project/openai/#history

**Comment by ryokan0123** [comment]
Issue のご報告ありがとうございます。
openai のアップデートを受けて、notebook がそのまま動くように version を指定する形に更新いたしました。
お知らせいただき、助かりました！
