### ISSUE TITLE
5.5.2　勾配累積　で説明内容で参照されているコードにgradient_accumulation_stepsがない

### ISSUE THREAD

**Issue by BridgesARGUS** [ghmagazine/llm-book#29]
興味深く勉強させていただいております。
p125におきまして「5.2節ではTrainingArgumentsにgradient_accumulation_stepsの値を指定して～」との記述がありますが、参照先と思われる5.2節で掲載されているTrainingArgumentsのパラメータにはgradient_accumulation_stepsが含まれていないと思います。
特に実行などに問題がないものですが、念のためご報告させていただきました。

**Comment by ryokan0123** [comment]
@BridgesARGUS さん、

ご連絡ありがとうございます。お返事が遅れましてすみませんでした。

ご指摘の通り、整合性が取れていない記述があること確認いたしました。
今後の改訂の際に修正させていただきます。

改めまして、このたびは本書をお手に取っていただき、また貴重なご指摘をいただきまして、誠にありがとうございました。
