### ISSUE TITLE
コードの抜け

### ISSUE THREAD

**Issue by tetsuomiyoshi** [ghmagazine/llm-book#30]
p158のIn[27]:ですが、最後の箇所で以下の記述が抜けてないでしょうか？
if best_score < scores["f1-score"]:
    best_score = scores["f1-score"]  #<--（抜け）
    best_model = model

同様に、p172のIn[40]:の最後の箇所ですが、
if best_score < scores["f1-score"]:
    best_score = scores["f1-score"]  #<--（抜け）
    best_model_crf = model_crf

**Comment by Kosuke-Yamada** [comment]
コードの抜けに関するご指摘ありがとうございます。
github上のコードを修正し、今後出版される書籍で対応いたします。
