### ISSUE TITLE
p.110 pipeline関数についてのコード内のコメントについて

### ISSUE THREAD

**Issue by BridgesARGUS** [ghmagazine/llm-book#43]
いつも参考にさせていただいております。
表題の件ですが、非常に細かいところなので本筋には影響がないと思いつつ念のため質問させていただきます。
ここではmodelとして"llm-book/bert-base-japanese-v3-jnli"を指定しているのですが、コメントでは# JSTSでファインチューニングしたモデルをpipelineで読み込む　とあります。
これはJNLIではないでしょうか？
もし私の理解不足でしたら申し訳ございません。

**Comment by ryokan0123** [comment]
@BridgesARGUS さん、

ご報告いただき、誠にありがとうございます。
ご指摘の通り、5.4.1 節末尾のコードスニペット内のコメントに誤植がございました。

誤: `# JSTSでファインチューニングしたモデルのpipelineを読み込む`
正: `# JNLIでファインチューニングしたモデルのpipelineを読み込む`

今後の改訂版にて修正させていただく所存です。
書籍の改善にお力添えいただき、誠にありがとうございます！

**Comment by BridgesARGUS** [comment]
重箱の隅をつつくような質問に対して対応してくださりありがとうございます。大局に影響のないもので大変恐縮です。先生の執筆される書籍を今後も楽しみにしております。
