### ISSUE TITLE
p.27 データの前処理 内の記述について

### ISSUE THREAD

**Issue by BridgesARGUS** [ghmagazine/llm-book#48]
興味深く拝読させていただいております。
表題の件なのですが、「その中からfew-shot学習に使用する四つの事例を取得しています。」という記述があるかと思います。
しかし該当コードを参照すると選択肢として0～4の計5つの事例が取得されているように見えます。
自分の勘違いの可能性もありますし、コードの挙動に影響はないのですが、念のためご連絡させていただきました。

**Comment by Kosuke-Yamada** [comment]
ご連絡ありがとうございます。また、拝読していただきありがとうございます。

> 該当コードを参照すると選択肢として0～4の計5つの事例が取得されている

もしかしたら、事例と選択肢に関して認識が間違ってしまっているかもしれません。

該当コードというのは、以下の箇所を指してますでしょうか？
選択肢はおっしゃる通り5つあります。
```
data["input"] = (
f"質問:{data['question']}\n" f"選択肢:0.{data['choice0']},1.{data['choice1']}," f"2.{data['choice2']},3.{data['choice3']}," f"4.{data['choice4']}"
```

few-shot学習に使用する**事例**というのは、「このような入力が来たらこのような応答を返してくださいという事例」を指します。
該当するコードは、以下の箇所に該当し、訓練用のデータセットから四つの事例を取得しています。
```
# 四つの few-shot 事例を取得する
few_shots = list(train_dataset)[:4]
```

実際に、P29からP30にかけての出力では、以下のような四つの事例をfew-shot学習用の事例として使用しています。

### 入力:
質問:4 輪でハンドルで操作し、ガソリンや電気で動く乗り物は? 選択肢:0. 自動車,1. 自転車,2. イヤホン,3. 飛行機,4. ライブ
### 応答: 0
### 入力:
質問:夏になったら着たくなるものは?
選択肢:0. 誘い水,1. 水着,2. 化粧水,3. 水すまし,4. 水筒
### 応答: 1
### 入力:
質問:声や楽器を使った芸術は?
選択肢:0. 猫,1. 音楽,2. 展覧会,3. 歌,4. スズメ
### 応答: 1
### 入力:
質問:売る物のことを何と言うか?
選択肢:0. 自転車,1. 鍋,2. 車,3. 飲み物,4. 商品
### 応答: 4

**Comment by BridgesARGUS** [comment]
ご回答ありがとうございます。5つの選択肢を持つ選択問題を4つという意味だったのですね。
自分も指していただいたコードをよく確認させていただいたところ、入力と応答のセットが4つになっておりました。
few_shots = list(train_dataset)[:4]
というところからも十分推し量れる内容でした。
自信の理解力のなさのため、貴重なお時間を割かせてしまい、大変申し訳ございませんでした。
